### ISSUE TITLE
Two album and book art styles may be broken

### ISSUE THREAD

**Issue by amiantos** [Haidra-Org/AI-Horde-Styles#43] opened 2024-12-05 00:28 UTC
Example images here: https://github.com/amiantos/AI-Horde-Styles-Previews/blob/main/categories/album_and_book_art.md

I don't think "children's book illustration" and "mastodon album cover" are working properly. I did not look into the issue myself so I can't suggest what it may be, but I assume the Loras aren't working. I tried regenerating the image multiple times to control for worker variance and they came out the same.

**Comment by arcaria** [comment] 2024-12-05 00:37
"children's book illustration" lora (https://civitai.com/models/670727?modelVersionId=755617) should work fine, it's small enough and not login-gated
"mastodon album cover" lora (https://civitai.com/models/685221/mastodon-album-cover?modelVersionId=766910) is also small enough but that one is login-gated

**Comment by arcaria** [comment] 2024-12-05 00:57
Did a quick test with fixed seed 1, prompt "tree", results were all basically the same image with only minor differences, so the loras are not being applied correctly. I see they are both for Flux Dev (I don't know if there are any loras for Schnell? haven't checked) but I have used some other Flux Dev loras before and they do work with our version of Schnell

**Comment by Efreak** [comment] 2024-12-05 08:18
It's possible that it's a worker issue. You can see the styles working as intended in the party: 

[Mastodon Album Cover](https://discord.com/channels/781145214752129095/1312185804206116906/1312523744492781579)

[children's book illustration](https://discord.com/channels/781145214752129095/1312185804206116906/1312505348128641074)

If you search discord for the style names, you'll likely find a free attempts at both styles that didn't work, so I'm guessing there's at least one worker that isn't downloading loras properly, or it could also be issues on Civitai's side.

**Comment by arcaria** [comment] 2024-12-05 08:25
There was no report of failed downloads on the API response, and like I said, all three images (with fixed seed) were slightly different from each other, but nothing that would indicate that it was the effect of a lora

**Comment by amiantos** [comment] 2024-12-05 19:30
Okey, I'll update my script and try to get successful previews to generate. I'll come back and close this issue then.

**Comment by Efreak** [comment] 2024-12-05 22:32
Children's illustration should be fixed with 678f3ecd8db5dde3bf0ccb70fb04c307031520e2

**Closed** 2024-12-05 23:17 UTC
